### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by dentra** [kuptservol/spring-telegram-bot-starter#2]
не хватает возможности подключаться через прокси.

в самом простом случае это по сути при вызове билдера в `UpdatesRepositoryConfiguration.getClient` добавить конфигурируемый useProxyProperties

**Comment by kuptservol** [comment]
Done. You can set proxy setting in configuration.yml like this

```
telegram.client.proxy:
    host: http://proxy_server
    port: 8090
```
